"""
Phase D: 30 additional Indian occupations across 4 new sectors closing the
NCS/igod.gov.in coverage gap.

Sectors added:
- Mining & Petroleum   (igod.gov.in: Coal & Mine, Petroleum/Oil/Gas)
- Utilities & Power    (igod.gov.in: Energy & Power; PLFS public utilities)
- Telecom & Communications  (igod.gov.in: Communications & IT)
- Renewable Energy & Green Tech  (Skill India Digital Hub focus sector)

Sources prefer ministry / regulator data where possible.
Employment values are conservative; doubt errs to the lower bound.
"""

NEW_OCCUPATIONS: list[dict] = [

    # ============ MINING & PETROLEUM (NEW SECTOR) ============
    {"slug": "coal-miners", "name": "Coal mine workers",
     "sector": "Mining & Petroleum", "value": 600000, "pay": 360000, "edu": 2, "hire": -1,
     "source": "Ministry of Coal + Coal India Ltd annual report",
     "source_url": "https://coal.nic.in/"},
    {"slug": "metal-ore-miners", "name": "Metal & iron ore miners",
     "sector": "Mining & Petroleum", "value": 350000, "pay": 320000, "edu": 2, "hire": 0,
     "source": "Indian Bureau of Mines",
     "source_url": "https://ibm.gov.in/"},
    {"slug": "stone-quarry-workers", "name": "Stone & limestone quarry workers",
     "sector": "Mining & Petroleum", "value": 800000, "pay": 180000, "edu": 1, "hire": -1,
     "source": "FIMI + state mines departments",
     "source_url": "https://fedmin.com/"},
    {"slug": "oil-gas-field-workers", "name": "Oil & gas field workers (upstream)",
     "sector": "Mining & Petroleum", "value": 145000, "pay": 720000, "edu": 3, "hire": 0,
     "source": "DGH + ONGC/OIL annual reports",
     "source_url": "https://dghindia.gov.in/"},
    {"slug": "petroleum-refinery-workers", "name": "Petroleum refinery & petrochemical workers",
     "sector": "Mining & Petroleum", "value": 95000, "pay": 950000, "edu": 3, "hire": 0,
     "source": "Petroleum Federation of India + IOCL/BPCL/HPCL filings",
     "source_url": "https://www.petrofed.org/"},
    {"slug": "mining-engineers", "name": "Mining engineers",
     "sector": "Mining & Petroleum", "value": 25000, "pay": 1100000, "edu": 4, "hire": 0,
     "source": "Mining Engineers Association of India",
     "source_url": "https://meai.in/"},
    {"slug": "geologists-explorers", "name": "Geologists & exploration scientists",
     "sector": "Mining & Petroleum", "value": 18000, "pay": 950000, "edu": 5, "hire": 0,
     "source": "Geological Survey of India",
     "source_url": "https://www.gsi.gov.in/"},
    {"slug": "petroleum-engineers", "name": "Petroleum engineers",
     "sector": "Mining & Petroleum", "value": 22000, "pay": 1500000, "edu": 4, "hire": 0,
     "source": "DGH + Society of Petroleum Engineers India",
     "source_url": "https://dghindia.gov.in/"},

    # ============ UTILITIES & POWER (NEW SECTOR) ============
    {"slug": "power-plant-operators", "name": "Power plant operators",
     "sector": "Utilities & Power", "value": 280000, "pay": 480000, "edu": 3, "hire": 0,
     "source": "Central Electricity Authority + NTPC/state genco filings",
     "source_url": "https://cea.nic.in/"},
    {"slug": "discom-staff", "name": "Electricity distribution (DISCOM) staff",
     "sector": "Utilities & Power", "value": 850000, "pay": 380000, "edu": 2, "hire": 0,
     "source": "Power Finance Corporation + state DISCOMs",
     "source_url": "https://www.pfcindia.com/"},
    {"slug": "water-utility-workers", "name": "Water utility & treatment workers",
     "sector": "Utilities & Power", "value": 320000, "pay": 230000, "edu": 2, "hire": 0,
     "source": "Ministry of Jal Shakti + Central Public Health Engineering",
     "source_url": "https://jalshakti-ddws.gov.in/"},
    {"slug": "sanitation-workers", "name": "Sanitation & sewage workers",
     "sector": "Utilities & Power", "value": 5000000, "pay": 130000, "edu": 1, "hire": 0,
     "source": "Swachh Bharat Mission + NCSK estimates",
     "source_url": "https://swachhbharatmission.gov.in/"},
    {"slug": "gas-pipeline-workers", "name": "Gas pipeline & CGD workers",
     "sector": "Utilities & Power", "value": 65000, "pay": 520000, "edu": 3, "hire": 1,
     "source": "PNGRB + CGD operators",
     "source_url": "https://www.pngrb.gov.in/"},
    {"slug": "utility-lineworkers", "name": "Electrical lineworkers (utility)",
     "sector": "Utilities & Power", "value": 380000, "pay": 280000, "edu": 2, "hire": 0,
     "source": "PSSC + Power Finance Corporation",
     "source_url": "https://www.skillpower.in/"},
    {"slug": "energy-engineers", "name": "Energy engineers (utilities)",
     "sector": "Utilities & Power", "value": 110000, "pay": 850000, "edu": 4, "hire": 1,
     "source": "CEA + Bureau of Energy Efficiency",
     "source_url": "https://beeindia.gov.in/"},
    {"slug": "meter-readers-billing", "name": "Utility billing & meter readers",
     "sector": "Utilities & Power", "value": 220000, "pay": 200000, "edu": 2, "hire": -2,
     "source": "PFC DISCOM operational data",
     "source_url": "https://www.pfcindia.com/"},

    # ============ TELECOM & COMMUNICATIONS (NEW SECTOR) ============
    {"slug": "telecom-tower-techs", "name": "Telecom tower & site technicians",
     "sector": "Telecom & Communications", "value": 380000, "pay": 280000, "edu": 3, "hire": 0,
     "source": "TSSC + DIPA",
     "source_url": "https://www.tsscindia.com/"},
    {"slug": "telecom-network-engineers", "name": "Telecom network engineers",
     "sector": "Telecom & Communications", "value": 220000, "pay": 850000, "edu": 4, "hire": 1,
     "source": "COAI + TSSC",
     "source_url": "https://coai.com/"},
    {"slug": "telecom-field-sales", "name": "Telecom field sales & retention",
     "sector": "Telecom & Communications", "value": 350000, "pay": 240000, "edu": 2, "hire": -1,
     "source": "TRAI subscriber report + COAI",
     "source_url": "https://www.trai.gov.in/"},
    {"slug": "optical-fibre-installers", "name": "Optical fibre installers (FTTH)",
     "sector": "Telecom & Communications", "value": 280000, "pay": 240000, "edu": 2, "hire": 2,
     "source": "BBNL + private ISP rollouts",
     "source_url": "https://bbnl.nic.in/"},
    {"slug": "spectrum-rf-engineers", "name": "RF / Spectrum engineers",
     "sector": "Telecom & Communications", "value": 35000, "pay": 1200000, "edu": 4, "hire": 1,
     "source": "WPC + DoT",
     "source_url": "https://dot.gov.in/"},
    {"slug": "broadcast-engineers", "name": "Broadcast & cable engineers",
     "sector": "Telecom & Communications", "value": 28000, "pay": 520000, "edu": 4, "hire": -1,
     "source": "Ministry of I&B + BECIL",
     "source_url": "https://mib.gov.in/"},
    {"slug": "submarine-cable-ops", "name": "Submarine & undersea cable operations",
     "sector": "Telecom & Communications", "value": 4000, "pay": 1500000, "edu": 4, "hire": 1,
     "source": "TRAI Submarine Cable Report",
     "source_url": "https://www.trai.gov.in/"},

    # ============ RENEWABLE ENERGY & GREEN TECH (NEW SECTOR) ============
    {"slug": "solar-pv-installers", "name": "Solar PV installers & technicians",
     "sector": "Renewable Energy & Green Tech", "value": 410000, "pay": 260000, "edu": 3, "hire": 3,
     "source": "MNRE + Skill Council for Green Jobs",
     "source_url": "https://mnre.gov.in/"},
    {"slug": "wind-turbine-techs", "name": "Wind turbine technicians",
     "sector": "Renewable Energy & Green Tech", "value": 32000, "pay": 450000, "edu": 3, "hire": 2,
     "source": "MNRE + Indian Wind Energy Association",
     "source_url": "https://inwea.org/"},
    {"slug": "ev-battery-mfg", "name": "EV battery manufacturing workers",
     "sector": "Renewable Energy & Green Tech", "value": 85000, "pay": 320000, "edu": 3, "hire": 3,
     "source": "ARAI + Society of Manufacturers of Electric Vehicles",
     "source_url": "https://www.smev.in/"},
    {"slug": "ev-charging-ops", "name": "EV charging station operators",
     "sector": "Renewable Energy & Green Tech", "value": 18000, "pay": 220000, "edu": 2, "hire": 3,
     "source": "Power Ministry EV-charging guidelines + state DISCOMs",
     "source_url": "https://powermin.gov.in/"},
    {"slug": "solar-pv-engineers", "name": "Solar PV engineers & designers",
     "sector": "Renewable Energy & Green Tech", "value": 65000, "pay": 720000, "edu": 4, "hire": 2,
     "source": "MNRE + Skill Council for Green Jobs",
     "source_url": "https://sscgj.in/"},
    {"slug": "esg-sustainability-analysts", "name": "Sustainability & ESG analysts",
     "sector": "Renewable Energy & Green Tech", "value": 25000, "pay": 1100000, "edu": 4, "hire": 3,
     "source": "SEBI BRSR + NSE-listed company filings",
     "source_url": "https://www.sebi.gov.in/legal/circulars/may-2021/business-responsibility-and-sustainability-reporting-by-listed-entities_50096.html"},
    {"slug": "green-hydrogen-techs", "name": "Green hydrogen technologists",
     "sector": "Renewable Energy & Green Tech", "value": 5000, "pay": 1500000, "edu": 5, "hire": 3,
     "source": "National Green Hydrogen Mission + MNRE",
     "source_url": "https://mnre.gov.in/national-green-hydrogen-mission/"},
]

# Add these sector names so merge_expansion.py accepts them.
NEW_SECTORS_V2 = {
    "Mining & Petroleum",
    "Utilities & Power",
    "Telecom & Communications",
    "Renewable Energy & Green Tech",
}
