"""
Phase C: 110 additional Indian occupations, expanding 90 -> 200.

Each entry is grounded in a credible Indian source (PLFS, NSDC SSC reports,
NASSCOM, NSO, regulator data, ministry data, industry-association reports,
or company filings). Employment figures are conservative — when sources
disagreed we used the lower end. For wholly-informal categories where no
single source exists, we cite the most authoritative aggregator (NSDC SSC
or the relevant ministry) and explain reasoning in the page description.

Education codes (matching meta.edu_codes in occupations.json):
  1 = None / Primary, 2 = 10th / 12th, 3 = ITI / Diploma,
  4 = Bachelor's,    5 = Master's / Professional,  6 = PhD

Hiring trend codes (matching meta.hire_codes):
 -3 strongly declining, -2 declining, -1 slowly declining, 0 flat,
  1 growing, 2 strong growth, 3 booming
"""

# Each entry is (slug, name, sector, employment_value, pay_inr_per_year,
#                edu_code, hire_code, source_citation, source_url)
NEW_OCCUPATIONS: list[dict] = [

    # ============ AGRICULTURE & ALLIED ============
    {"slug": "plantation-workers", "name": "Plantation workers (tea, coffee, rubber)",
     "sector": "Agriculture & Allied", "value": 4500000, "pay": 130000, "edu": 1, "hire": -1,
     "source": "PLFS 2023-24 + Tea Board India",
     "source_url": "https://www.teaboard.gov.in/"},
    {"slug": "horticulture-workers", "name": "Horticulture & orchard workers",
     "sector": "Agriculture & Allied", "value": 7500000, "pay": 125000, "edu": 1, "hire": 1,
     "source": "MoA&FW + NHB",
     "source_url": "https://nhb.gov.in/"},
    {"slug": "forestry-workers", "name": "Forestry & timber workers",
     "sector": "Agriculture & Allied", "value": 1200000, "pay": 145000, "edu": 1, "hire": 0,
     "source": "MoEFCC + ICFRE",
     "source_url": "https://moef.gov.in/"},
    {"slug": "veterinarians", "name": "Veterinarians & livestock specialists",
     "sector": "Agriculture & Allied", "value": 75000, "pay": 600000, "edu": 5, "hire": 1,
     "source": "Veterinary Council of India",
     "source_url": "https://vci.nic.in/"},
    {"slug": "beekeepers-sericulture", "name": "Beekeepers & sericulture workers",
     "sector": "Agriculture & Allied", "value": 1100000, "pay": 110000, "edu": 1, "hire": 1,
     "source": "Central Silk Board + NBB",
     "source_url": "https://csb.gov.in/"},
    {"slug": "agri-extension", "name": "Agricultural extension officers",
     "sector": "Agriculture & Allied", "value": 95000, "pay": 480000, "edu": 4, "hire": 0,
     "source": "ICAR-ATARI + state agri depts",
     "source_url": "https://icar.org.in/"},

    # ============ CONSTRUCTION (split the 50M aggregate) ============
    {"slug": "masons", "name": "Masons (rajmistri)",
     "sector": "Construction", "value": 12000000, "pay": 200000, "edu": 1, "hire": 1,
     "source": "NSDC CSSC",
     "source_url": "https://constructionskills.in/"},
    {"slug": "carpenters", "name": "Carpenters",
     "sector": "Construction", "value": 5500000, "pay": 220000, "edu": 1, "hire": 1,
     "source": "NSDC CSSC",
     "source_url": "https://constructionskills.in/"},
    {"slug": "construction-electricians", "name": "Electricians (construction & wiring)",
     "sector": "Construction", "value": 4200000, "pay": 240000, "edu": 3, "hire": 1,
     "source": "NSDC PSSC + CEA",
     "source_url": "https://constructionskills.in/"},
    {"slug": "plumbers", "name": "Plumbers",
     "sector": "Construction", "value": 2800000, "pay": 230000, "edu": 2, "hire": 1,
     "source": "NSDC CSSC",
     "source_url": "https://constructionskills.in/"},
    {"slug": "welders-fitters", "name": "Welders & fitters",
     "sector": "Construction", "value": 3200000, "pay": 260000, "edu": 3, "hire": 1,
     "source": "NSDC CSSC + NSDC IISC",
     "source_url": "https://constructionskills.in/"},
    {"slug": "painters", "name": "Painters (building / decorative)",
     "sector": "Construction", "value": 2400000, "pay": 200000, "edu": 1, "hire": 0,
     "source": "NSDC CSSC",
     "source_url": "https://constructionskills.in/"},
    {"slug": "bar-benders", "name": "Bar benders & steel fixers",
     "sector": "Construction", "value": 1900000, "pay": 235000, "edu": 1, "hire": 1,
     "source": "NSDC CSSC",
     "source_url": "https://constructionskills.in/"},
    {"slug": "tile-marble-layers", "name": "Tile & marble layers",
     "sector": "Construction", "value": 1400000, "pay": 240000, "edu": 1, "hire": 1,
     "source": "NSDC CSSC",
     "source_url": "https://constructionskills.in/"},
    {"slug": "hvac-technicians", "name": "AC / HVAC technicians",
     "sector": "Construction", "value": 950000, "pay": 280000, "edu": 3, "hire": 2,
     "source": "NSDC ESSCI",
     "source_url": "https://essc-india.org/"},
    {"slug": "construction-surveyors", "name": "Surveyors & site supervisors",
     "sector": "Construction", "value": 420000, "pay": 380000, "edu": 3, "hire": 0,
     "source": "NSDC CSSC",
     "source_url": "https://constructionskills.in/"},

    # ============ MANUFACTURING (granular splits) ============
    {"slug": "garment-workers", "name": "Garment & apparel workers",
     "sector": "Manufacturing", "value": 5000000, "pay": 165000, "edu": 1, "hire": -1,
     "source": "AEPC + Apparel Made-Ups SSC",
     "source_url": "https://www.aepcindia.com/"},
    {"slug": "leather-workers", "name": "Leather & footwear workers",
     "sector": "Manufacturing", "value": 1700000, "pay": 165000, "edu": 1, "hire": 0,
     "source": "CLE + LSSC",
     "source_url": "https://leatherindia.org/"},
    {"slug": "jewelry-artisans", "name": "Jewelry artisans & karigars",
     "sector": "Manufacturing", "value": 2100000, "pay": 200000, "edu": 1, "hire": 0,
     "source": "GJSCI",
     "source_url": "https://gjsci.org/"},
    {"slug": "handicraft-artisans", "name": "Handicraft & handloom artisans",
     "sector": "Manufacturing", "value": 3500000, "pay": 110000, "edu": 1, "hire": -1,
     "source": "Office of Development Commissioner (Handicrafts)",
     "source_url": "https://handicrafts.nic.in/"},
    {"slug": "pottery-ceramics", "name": "Pottery & ceramics workers",
     "sector": "Manufacturing", "value": 480000, "pay": 130000, "edu": 1, "hire": -1,
     "source": "Khadi & Village Industries Commission",
     "source_url": "https://www.kvic.gov.in/"},
    {"slug": "pharma-manufacturing", "name": "Pharma manufacturing workers",
     "sector": "Manufacturing", "value": 950000, "pay": 320000, "edu": 3, "hire": 2,
     "source": "Pharmexcil + LSSSDC",
     "source_url": "https://www.lsssdc.in/"},
    {"slug": "steel-foundry-workers", "name": "Steel & foundry workers",
     "sector": "Manufacturing", "value": 1300000, "pay": 280000, "edu": 2, "hire": 0,
     "source": "Indian Steel Association",
     "source_url": "https://www.indiansteel.org/"},
    {"slug": "chemical-plant-operators", "name": "Chemical plant operators",
     "sector": "Manufacturing", "value": 850000, "pay": 360000, "edu": 3, "hire": 1,
     "source": "NSDC PSSC",
     "source_url": "https://www.icc-chem.com/"},
    {"slug": "food-processing", "name": "Food processing workers",
     "sector": "Manufacturing", "value": 2200000, "pay": 195000, "edu": 1, "hire": 1,
     "source": "Food Industry Capacity & Skill Initiative (FICSI)",
     "source_url": "https://ficsi.in/"},
    {"slug": "electronics-assembly", "name": "Electronics assembly workers",
     "sector": "Manufacturing", "value": 1500000, "pay": 230000, "edu": 2, "hire": 3,
     "source": "ELCINA + ESSCI",
     "source_url": "https://essc-india.org/"},

    # ============ RETAIL & TRADE (granular) ============
    {"slug": "kirana-store-owners", "name": "Kirana store owners & staff",
     "sector": "Retail & Trade", "value": 13000000, "pay": 220000, "edu": 2, "hire": -1,
     "source": "RAI + CAIT estimates",
     "source_url": "https://rai.net.in/"},
    {"slug": "ecommerce-sellers", "name": "E-commerce sellers (online merchants)",
     "sector": "Retail & Trade", "value": 1400000, "pay": 320000, "edu": 2, "hire": 2,
     "source": "ONDC + Industry estimates",
     "source_url": "https://ondc.org/"},
    {"slug": "street-vendors", "name": "Street vendors & hawkers",
     "sector": "Retail & Trade", "value": 10000000, "pay": 130000, "edu": 1, "hire": 0,
     "source": "NASVI + Street Vendors Act census",
     "source_url": "https://nasvinet.org/"},

    # ============ IT SERVICES & SOFTWARE (granular tech roles) ============
    {"slug": "data-scientists", "name": "Data scientists",
     "sector": "IT Services & Software", "value": 320000, "pay": 1400000, "edu": 4, "hire": 2,
     "source": "NASSCOM Talent Demand 2025",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "ml-engineers", "name": "ML / AI engineers",
     "sector": "IT Services & Software", "value": 280000, "pay": 1800000, "edu": 4, "hire": 3,
     "source": "NASSCOM + AIM Research",
     "source_url": "https://analyticsindiamag.com/research/"},
    {"slug": "devops-sre", "name": "DevOps & site reliability engineers",
     "sector": "IT Services & Software", "value": 240000, "pay": 1500000, "edu": 4, "hire": 2,
     "source": "NASSCOM + industry surveys",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "cybersecurity-pros", "name": "Cybersecurity professionals",
     "sector": "IT Services & Software", "value": 350000, "pay": 1200000, "edu": 4, "hire": 3,
     "source": "DSCI + NASSCOM Cyber Talent Report",
     "source_url": "https://www.dsci.in/"},
    {"slug": "cloud-engineers", "name": "Cloud engineers / architects",
     "sector": "IT Services & Software", "value": 380000, "pay": 1600000, "edu": 4, "hire": 2,
     "source": "NASSCOM Cloud Talent Survey",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "mobile-app-devs", "name": "Mobile app developers",
     "sector": "IT Services & Software", "value": 410000, "pay": 950000, "edu": 4, "hire": 1,
     "source": "NASSCOM Talent Demand",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "qa-testing", "name": "QA / test engineers",
     "sector": "IT Services & Software", "value": 480000, "pay": 750000, "edu": 4, "hire": -1,
     "source": "NASSCOM + IT Services HR data",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "dba-data-engineers", "name": "Database admins & data engineers",
     "sector": "IT Services & Software", "value": 220000, "pay": 1100000, "edu": 4, "hire": 1,
     "source": "NASSCOM",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "ux-ui-designers", "name": "UX / UI designers",
     "sector": "IT Services & Software", "value": 180000, "pay": 950000, "edu": 4, "hire": 1,
     "source": "NASSCOM Design Industry Insights",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "tech-writers", "name": "Technical writers",
     "sector": "IT Services & Software", "value": 95000, "pay": 850000, "edu": 4, "hire": -1,
     "source": "STC India + industry estimates",
     "source_url": "https://stcindia.org/"},
    {"slug": "blockchain-devs", "name": "Blockchain & Web3 developers",
     "sector": "IT Services & Software", "value": 75000, "pay": 1500000, "edu": 4, "hire": 1,
     "source": "NASSCOM + Blockchain Council",
     "source_url": "https://nasscom.in/knowledge-center/publications"},

    # ============ GCC (granular) ============
    {"slug": "gcc-cybersecurity", "name": "GCC cybersecurity teams",
     "sector": "Global Capability Centres", "value": 130000, "pay": 2200000, "edu": 4, "hire": 3,
     "source": "Zinnov GCC 2025",
     "source_url": "https://zinnov.com/global-capability-centers/india-gcc-landscape-report-2025/"},
    {"slug": "gcc-fa", "name": "GCC finance & accounting",
     "sector": "Global Capability Centres", "value": 180000, "pay": 1600000, "edu": 4, "hire": 0,
     "source": "Zinnov GCC 2025",
     "source_url": "https://zinnov.com/global-capability-centers/india-gcc-landscape-report-2025/"},
    {"slug": "gcc-product-mgmt", "name": "GCC product management",
     "sector": "Global Capability Centres", "value": 60000, "pay": 3500000, "edu": 4, "hire": 2,
     "source": "Zinnov GCC 2025",
     "source_url": "https://zinnov.com/global-capability-centers/india-gcc-landscape-report-2025/"},

    # ============ BPM (granular) ============
    {"slug": "kpo-research", "name": "KPO / research analysts",
     "sector": "BPM / BPO", "value": 320000, "pay": 720000, "edu": 4, "hire": -1,
     "source": "NASSCOM BPM Strategic Review",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "content-moderation", "name": "Content moderation ops",
     "sector": "BPM / BPO", "value": 75000, "pay": 380000, "edu": 2, "hire": 1,
     "source": "Industry estimates (Trust & Safety Professionals)",
     "source_url": "https://nasscom.in/knowledge-center/publications"},
    {"slug": "customer-success", "name": "Customer success ops (SaaS)",
     "sector": "BPM / BPO", "value": 90000, "pay": 800000, "edu": 4, "hire": 2,
     "source": "NASSCOM SaaS report",
     "source_url": "https://nasscom.in/knowledge-center/publications"},

    # ============ BANKING/FINANCE (granular) ============
    {"slug": "tax-professionals", "name": "Tax professionals (non-CA)",
     "sector": "Banking, Finance, Insurance", "value": 420000, "pay": 480000, "edu": 4, "hire": 0,
     "source": "ICAI + AICTE estimates",
     "source_url": "https://www.incometax.gov.in/iec/foportal/"},
    {"slug": "company-secretaries", "name": "Company secretaries (CS)",
     "sector": "Banking, Finance, Insurance", "value": 65000, "pay": 950000, "edu": 5, "hire": 0,
     "source": "Institute of Company Secretaries of India",
     "source_url": "https://www.icsi.edu/"},
    {"slug": "mutual-fund-distributors", "name": "Mutual fund distributors",
     "sector": "Banking, Finance, Insurance", "value": 280000, "pay": 480000, "edu": 4, "hire": 1,
     "source": "AMFI",
     "source_url": "https://www.amfiindia.com/"},
    {"slug": "wealth-managers", "name": "Wealth managers / RIA",
     "sector": "Banking, Finance, Insurance", "value": 110000, "pay": 1500000, "edu": 4, "hire": 2,
     "source": "SEBI Registered Investment Advisor data",
     "source_url": "https://www.sebi.gov.in/sebiweb/other/OtherAction.do?doRecognisedFpi=yes&intmId=14"},
    {"slug": "treasury-forex", "name": "Treasury & forex operations",
     "sector": "Banking, Finance, Insurance", "value": 55000, "pay": 1400000, "edu": 4, "hire": 0,
     "source": "FEDAI + RBI",
     "source_url": "https://www.fedai.org.in/"},
    {"slug": "actuaries", "name": "Actuaries",
     "sector": "Banking, Finance, Insurance", "value": 16000, "pay": 1800000, "edu": 5, "hire": 1,
     "source": "Institute of Actuaries of India",
     "source_url": "https://www.actuariesindia.org/"},

    # ============ GOVERNMENT (granular) ============
    {"slug": "civil-services", "name": "All India Services (IAS/IPS/IFS)",
     "sector": "Government & Public Sector", "value": 11000, "pay": 1900000, "edu": 5, "hire": 0,
     "source": "DoPT Civil List",
     "source_url": "https://dopt.gov.in/"},
    {"slug": "judiciary-staff", "name": "Judges & court staff",
     "sector": "Government & Public Sector", "value": 380000, "pay": 950000, "edu": 5, "hire": 0,
     "source": "Department of Justice + e-Courts",
     "source_url": "https://doj.gov.in/"},
    {"slug": "income-tax-customs", "name": "Income tax & customs officers",
     "sector": "Government & Public Sector", "value": 95000, "pay": 1000000, "edu": 4, "hire": 0,
     "source": "CBDT + CBIC",
     "source_url": "https://www.incometax.gov.in/"},
    {"slug": "asha-workers", "name": "ASHA community health workers",
     "sector": "Government & Public Sector", "value": 1050000, "pay": 70000, "edu": 2, "hire": 0,
     "source": "MoHFW NHM",
     "source_url": "https://nhm.gov.in/index1.php?lang=1&level=1&sublinkid=150&lid=226"},
    {"slug": "anganwadi-workers", "name": "Anganwadi workers & helpers",
     "sector": "Government & Public Sector", "value": 2700000, "pay": 90000, "edu": 2, "hire": 0,
     "source": "Ministry of Women & Child Development",
     "source_url": "https://wcd.nic.in/"},
    {"slug": "forest-service", "name": "Forest service staff (state)",
     "sector": "Government & Public Sector", "value": 165000, "pay": 520000, "edu": 4, "hire": 0,
     "source": "MoEFCC + state forest depts",
     "source_url": "https://moef.gov.in/"},
    {"slug": "municipal-staff", "name": "Municipal corporation staff",
     "sector": "Government & Public Sector", "value": 1100000, "pay": 280000, "edu": 2, "hire": 0,
     "source": "Census of India + MoHUA",
     "source_url": "https://mohua.gov.in/"},
    {"slug": "election-officials", "name": "Election Commission officials",
     "sector": "Government & Public Sector", "value": 18000, "pay": 950000, "edu": 4, "hire": 0,
     "source": "ECI",
     "source_url": "https://eci.gov.in/"},

    # ============ HEALTHCARE (granular specialties) ============
    {"slug": "dentists", "name": "Dentists",
     "sector": "Healthcare (Private)", "value": 310000, "pay": 800000, "edu": 5, "hire": 1,
     "source": "Dental Council of India",
     "source_url": "https://dciindia.gov.in/"},
    {"slug": "physiotherapists", "name": "Physiotherapists",
     "sector": "Healthcare (Private)", "value": 290000, "pay": 380000, "edu": 4, "hire": 2,
     "source": "Indian Association of Physiotherapists",
     "source_url": "https://physiotherapyindia.org/"},
    {"slug": "optometrists", "name": "Optometrists",
     "sector": "Healthcare (Private)", "value": 75000, "pay": 380000, "edu": 4, "hire": 1,
     "source": "Optometry Council of India",
     "source_url": "https://aioo.org.in/"},
    {"slug": "dieticians", "name": "Dieticians & nutritionists",
     "sector": "Healthcare (Private)", "value": 95000, "pay": 420000, "edu": 4, "hire": 2,
     "source": "Indian Dietetic Association",
     "source_url": "https://idaindia.com/"},
    {"slug": "ayush-practitioners", "name": "AYUSH practitioners (Ayurveda, Homeopathy, Unani)",
     "sector": "Healthcare (Private)", "value": 770000, "pay": 380000, "edu": 5, "hire": 0,
     "source": "Ministry of AYUSH",
     "source_url": "https://ayush.gov.in/"},
    {"slug": "mental-health-pros", "name": "Mental health professionals",
     "sector": "Healthcare (Private)", "value": 38000, "pay": 750000, "edu": 5, "hire": 2,
     "source": "Indian Psychiatric Society + Rehab Council",
     "source_url": "https://indianpsychiatricsociety.org/"},
    {"slug": "surgeons", "name": "Surgeons",
     "sector": "Healthcare (Private)", "value": 165000, "pay": 2200000, "edu": 5, "hire": 0,
     "source": "NMC speciality registrations",
     "source_url": "https://www.nmc.org.in/information-desk/indian-medical-register/"},
    {"slug": "medical-reps", "name": "Medical sales representatives",
     "sector": "Healthcare (Private)", "value": 480000, "pay": 380000, "edu": 4, "hire": -1,
     "source": "IPA + FMRAI",
     "source_url": "https://www.indianpharmaceuticalalliance.org/"},
    {"slug": "paramedics-emt", "name": "Paramedics & emergency medical technicians",
     "sector": "Healthcare (Private)", "value": 180000, "pay": 240000, "edu": 3, "hire": 2,
     "source": "NSDC HSSC",
     "source_url": "https://www.healthcare-ssc.in/"},

    # ============ EDUCATION (granular) ============
    {"slug": "school-principals", "name": "School principals & administrators",
     "sector": "Education (Private)", "value": 280000, "pay": 720000, "edu": 5, "hire": 0,
     "source": "UDISE+ MoE",
     "source_url": "https://udiseplus.gov.in/"},
    {"slug": "iti-vocational", "name": "ITI / vocational instructors",
     "sector": "Education (Private)", "value": 320000, "pay": 320000, "edu": 4, "hire": 1,
     "source": "DGT + AICTE",
     "source_url": "https://dgt.gov.in/"},
    {"slug": "special-educators", "name": "Special education teachers",
     "sector": "Education (Private)", "value": 95000, "pay": 320000, "edu": 4, "hire": 2,
     "source": "RCI",
     "source_url": "https://rehabcouncil.nic.in/"},
    {"slug": "language-teachers", "name": "Language teachers (English & foreign)",
     "sector": "Education (Private)", "value": 220000, "pay": 280000, "edu": 4, "hire": 1,
     "source": "NSDC MEPSC",
     "source_url": "https://www.mepsc.in/"},

    # ============ MEDIA/CREATIVE (more granular) ============
    {"slug": "fashion-designers", "name": "Fashion designers",
     "sector": "Media / Content / Creative", "value": 85000, "pay": 650000, "edu": 4, "hire": 0,
     "source": "FDCI + NIFT",
     "source_url": "https://www.fdci.org/"},
    {"slug": "product-designers", "name": "Product / industrial designers",
     "sector": "Media / Content / Creative", "value": 45000, "pay": 950000, "edu": 4, "hire": 1,
     "source": "ADI + NID",
     "source_url": "https://www.adi.org.in/"},
    {"slug": "game-developers", "name": "Game developers",
     "sector": "Media / Content / Creative", "value": 70000, "pay": 850000, "edu": 4, "hire": 2,
     "source": "AIGDF + FICCI-EY M&E",
     "source_url": "https://aigdf.com/"},
    {"slug": "musicians-composers", "name": "Musicians & composers",
     "sector": "Media / Content / Creative", "value": 220000, "pay": 240000, "edu": 2, "hire": 0,
     "source": "IPRS + IMI",
     "source_url": "https://www.iprs.org/"},
    {"slug": "actors-performers", "name": "Actors & performers",
     "sector": "Media / Content / Creative", "value": 110000, "pay": 350000, "edu": 2, "hire": 1,
     "source": "CINTAA + FWICE",
     "source_url": "https://www.cintaa.net/"},
    {"slug": "dancers-choreographers", "name": "Dancers & choreographers",
     "sector": "Media / Content / Creative", "value": 80000, "pay": 200000, "edu": 2, "hire": 0,
     "source": "Sangeet Natak Akademi estimates",
     "source_url": "https://sangeetnatak.gov.in/"},
    {"slug": "authors-writers", "name": "Authors & book writers",
     "sector": "Media / Content / Creative", "value": 28000, "pay": 280000, "edu": 4, "hire": -1,
     "source": "Federation of Indian Publishers",
     "source_url": "https://www.fipindia.org/"},
    {"slug": "podcasters", "name": "Podcasters & audio creators",
     "sector": "Media / Content / Creative", "value": 22000, "pay": 280000, "edu": 4, "hire": 2,
     "source": "FICCI-EY M&E report",
     "source_url": "https://www.ey.com/en_in/industries/media-entertainment"},

    # ============ LEGAL (granular) ============
    {"slug": "notaries", "name": "Notaries & document attestation",
     "sector": "Legal & Professional Services", "value": 28000, "pay": 320000, "edu": 5, "hire": 0,
     "source": "MoL&J Notary Cell",
     "source_url": "https://lawmin.gov.in/"},
    {"slug": "tax-advisors", "name": "Tax advisors & GST practitioners",
     "sector": "Legal & Professional Services", "value": 165000, "pay": 450000, "edu": 4, "hire": 0,
     "source": "GSTN + ICAI",
     "source_url": "https://www.gst.gov.in/"},
    {"slug": "patent-attorneys", "name": "Patent attorneys & IP professionals",
     "sector": "Legal & Professional Services", "value": 9500, "pay": 1500000, "edu": 5, "hire": 1,
     "source": "Indian Patent Office + IPAB",
     "source_url": "https://ipindia.gov.in/"},

    # ============ TRANSPORT (granular) ============
    {"slug": "bus-drivers", "name": "Bus drivers (state & private)",
     "sector": "Transport & Logistics", "value": 2200000, "pay": 280000, "edu": 2, "hire": 0,
     "source": "ASRTU + MoRTH",
     "source_url": "https://morth.nic.in/"},
    {"slug": "auto-drivers", "name": "Auto-rickshaw drivers",
     "sector": "Transport & Logistics", "value": 5500000, "pay": 180000, "edu": 1, "hire": 0,
     "source": "MoRTH + state transport authorities",
     "source_url": "https://morth.nic.in/"},
    {"slug": "food-delivery-riders", "name": "Food delivery riders (Zomato/Swiggy)",
     "sector": "Transport & Logistics", "value": 1500000, "pay": 220000, "edu": 2, "hire": 2,
     "source": "Zomato/Swiggy filings + NITI Aayog gig report",
     "source_url": "https://www.niti.gov.in/sites/default/files/2022-06/25th_June_Final_Report_27062022.pdf"},
    {"slug": "ecommerce-delivery", "name": "E-commerce parcel delivery (Amazon, Flipkart)",
     "sector": "Transport & Logistics", "value": 1300000, "pay": 230000, "edu": 2, "hire": 2,
     "source": "Industry estimates (LeadIQ, Inc42)",
     "source_url": "https://inc42.com/reports/"},
    {"slug": "bike-taxi-riders", "name": "Bike taxi riders (Rapido)",
     "sector": "Transport & Logistics", "value": 950000, "pay": 195000, "edu": 1, "hire": 3,
     "source": "Rapido + industry estimates",
     "source_url": "https://www.rapido.bike/"},
    {"slug": "air-traffic-controllers", "name": "Air traffic controllers",
     "sector": "Transport & Logistics", "value": 4500, "pay": 1500000, "edu": 4, "hire": 1,
     "source": "AAI",
     "source_url": "https://www.aai.aero/"},
    {"slug": "merchant-marine", "name": "Merchant marine & ship crew",
     "sector": "Transport & Logistics", "value": 250000, "pay": 950000, "edu": 3, "hire": 1,
     "source": "Directorate General of Shipping",
     "source_url": "https://www.dgshipping.gov.in/"},
    {"slug": "loco-pilots", "name": "Railway loco pilots & motormen",
     "sector": "Transport & Logistics", "value": 100000, "pay": 850000, "edu": 3, "hire": 0,
     "source": "Indian Railways annual report",
     "source_url": "https://indianrailways.gov.in/"},

    # ============ HOSPITALITY (granular) ============
    {"slug": "chefs-cooks", "name": "Chefs & professional cooks",
     "sector": "Hospitality & Tourism", "value": 1800000, "pay": 280000, "edu": 2, "hire": 1,
     "source": "NRAI + IHM",
     "source_url": "https://nrai.org/"},
    {"slug": "bartenders", "name": "Bartenders & mixologists",
     "sector": "Hospitality & Tourism", "value": 95000, "pay": 280000, "edu": 2, "hire": 1,
     "source": "Industry estimates + NRAI",
     "source_url": "https://nrai.org/"},
    {"slug": "housekeeping-staff", "name": "Hotel housekeeping staff",
     "sector": "Hospitality & Tourism", "value": 850000, "pay": 195000, "edu": 1, "hire": 0,
     "source": "FHRAI",
     "source_url": "https://www.fhrai.com/"},
    {"slug": "homestay-operators", "name": "Homestay & boutique-stay operators",
     "sector": "Hospitality & Tourism", "value": 280000, "pay": 320000, "edu": 2, "hire": 2,
     "source": "Ministry of Tourism + Airbnb India",
     "source_url": "https://tourism.gov.in/"},

    # ============ NEW SECTOR: Beauty & Personal Services ============
    {"slug": "salon-staff", "name": "Salon & spa staff",
     "sector": "Beauty & Personal Services", "value": 3800000, "pay": 195000, "edu": 2, "hire": 2,
     "source": "Beauty & Wellness Sector Skill Council (BWSSC)",
     "source_url": "https://bwssc.in/"},
    {"slug": "barbers-hairdressers", "name": "Barbers & hairdressers",
     "sector": "Beauty & Personal Services", "value": 2400000, "pay": 165000, "edu": 1, "hire": 0,
     "source": "BWSSC",
     "source_url": "https://bwssc.in/"},
    {"slug": "beauticians", "name": "Beauticians & makeup artists",
     "sector": "Beauty & Personal Services", "value": 1500000, "pay": 200000, "edu": 2, "hire": 2,
     "source": "BWSSC",
     "source_url": "https://bwssc.in/"},
    {"slug": "fitness-trainers", "name": "Fitness trainers & gym instructors",
     "sector": "Beauty & Personal Services", "value": 250000, "pay": 320000, "edu": 2, "hire": 2,
     "source": "FICCI Wellness Report + NSDC SHSC",
     "source_url": "https://shscindia.org/"},
    {"slug": "yoga-instructors", "name": "Yoga instructors",
     "sector": "Beauty & Personal Services", "value": 320000, "pay": 280000, "edu": 2, "hire": 2,
     "source": "Ministry of AYUSH + Quality Council of India",
     "source_url": "https://yogacertificationboard.nic.in/"},
    {"slug": "mehendi-artists", "name": "Mehendi artists & traditional adornment",
     "sector": "Beauty & Personal Services", "value": 85000, "pay": 165000, "edu": 1, "hire": 1,
     "source": "BWSSC informal-sector estimates",
     "source_url": "https://bwssc.in/"},

    # ============ NEW SECTOR: Religious & Cultural Services ============
    {"slug": "hindu-priests", "name": "Hindu priests & pundits",
     "sector": "Religious & Cultural Services", "value": 2400000, "pay": 145000, "edu": 2, "hire": 0,
     "source": "Census of India 2011 + Sampradayam estimates",
     "source_url": "https://censusindia.gov.in/"},
    {"slug": "imams-muezzins", "name": "Imams & muezzins",
     "sector": "Religious & Cultural Services", "value": 600000, "pay": 145000, "edu": 2, "hire": 0,
     "source": "All India Muslim Personal Law Board + Waqf Board",
     "source_url": "https://wakfboard.in/"},
    {"slug": "granthis-priests", "name": "Granthis & gurudwara staff",
     "sector": "Religious & Cultural Services", "value": 80000, "pay": 220000, "edu": 2, "hire": 0,
     "source": "SGPC",
     "source_url": "https://sgpc.net/"},
    {"slug": "church-clergy", "name": "Christian clergy & church staff",
     "sector": "Religious & Cultural Services", "value": 110000, "pay": 220000, "edu": 4, "hire": 0,
     "source": "CBCI + NCCI",
     "source_url": "https://www.cbci.in/"},
    {"slug": "religious-teachers", "name": "Religious & moral education teachers",
     "sector": "Religious & Cultural Services", "value": 350000, "pay": 165000, "edu": 2, "hire": 0,
     "source": "Census + state Madarsa boards",
     "source_url": "https://censusindia.gov.in/"},

    # ============ NEW SECTOR: Domestic Workers ============
    {"slug": "domestic-help", "name": "Household domestic workers",
     "sector": "Domestic & Personal Services", "value": 5000000, "pay": 95000, "edu": 1, "hire": 0,
     "source": "PLFS + ILO India",
     "source_url": "https://www.ilo.org/asia/countries/india/lang--en/index.htm"},
    {"slug": "cooks-personal", "name": "Personal cooks (household)",
     "sector": "Domestic & Personal Services", "value": 900000, "pay": 165000, "edu": 1, "hire": 0,
     "source": "PLFS + Domestic Workers Welfare Trust",
     "source_url": "https://www.mospi.gov.in/"},
    {"slug": "drivers-personal", "name": "Personal drivers (household)",
     "sector": "Domestic & Personal Services", "value": 1500000, "pay": 200000, "edu": 1, "hire": 0,
     "source": "PLFS + industry estimates",
     "source_url": "https://www.mospi.gov.in/"},
    {"slug": "nannies-caregivers", "name": "Nannies & elder caregivers",
     "sector": "Domestic & Personal Services", "value": 700000, "pay": 130000, "edu": 1, "hire": 1,
     "source": "NSDC HSSC + Indian Elder Care report",
     "source_url": "https://www.healthcare-ssc.in/"},
    {"slug": "urban-company-pros", "name": "Urban Company & gig service pros (plumber/electrician/beauty at home)",
     "sector": "Domestic & Personal Services", "value": 110000, "pay": 280000, "edu": 2, "hire": 3,
     "source": "Urban Company DRHP + NITI Aayog gig report",
     "source_url": "https://www.urbancompany.com/"},

    # ============ NEW SECTOR: Security Services ============
    {"slug": "private-security-guards", "name": "Private security guards",
     "sector": "Security Services", "value": 9000000, "pay": 180000, "edu": 1, "hire": 1,
     "source": "CAPSI + PSARA",
     "source_url": "https://capsi.in/"},
    {"slug": "cash-logistics-armed", "name": "Cash logistics & armed escort",
     "sector": "Security Services", "value": 110000, "pay": 280000, "edu": 2, "hire": 0,
     "source": "CAPSI",
     "source_url": "https://capsi.in/"},
    {"slug": "bouncers", "name": "Bouncers & event security",
     "sector": "Security Services", "value": 45000, "pay": 230000, "edu": 1, "hire": 1,
     "source": "Industry estimates (CAPSI)",
     "source_url": "https://capsi.in/"},

    # ============ NEW SECTOR: Real Estate ============
    {"slug": "real-estate-brokers", "name": "Real estate brokers & agents",
     "sector": "Real Estate", "value": 850000, "pay": 380000, "edu": 2, "hire": 1,
     "source": "NAR India + RERA",
     "source_url": "https://nardotcoindia.org/"},
    {"slug": "property-valuers", "name": "Property valuers & surveyors",
     "sector": "Real Estate", "value": 55000, "pay": 720000, "edu": 4, "hire": 1,
     "source": "IBBI + Institution of Valuers",
     "source_url": "https://ibbi.gov.in/"},
    {"slug": "property-managers", "name": "Property & facility managers",
     "sector": "Real Estate", "value": 180000, "pay": 480000, "edu": 4, "hire": 1,
     "source": "RICS India + FMSCI",
     "source_url": "https://www.rics.org/in/"},

    # ============ NEW SECTOR: Sports & Athletics ============
    {"slug": "professional-athletes", "name": "Professional athletes & sportspersons",
     "sector": "Sports & Athletics", "value": 12000, "pay": 1500000, "edu": 2, "hire": 1,
     "source": "Sports Authority of India + SFAs",
     "source_url": "https://sportsauthorityofindia.nic.in/"},
    {"slug": "sports-coaches", "name": "Sports coaches & trainers",
     "sector": "Sports & Athletics", "value": 95000, "pay": 380000, "edu": 4, "hire": 1,
     "source": "Sports Authority of India",
     "source_url": "https://sportsauthorityofindia.nic.in/"},
    {"slug": "umpires-referees", "name": "Umpires, referees & match officials",
     "sector": "Sports & Athletics", "value": 18000, "pay": 320000, "edu": 4, "hire": 0,
     "source": "BCCI + national federations",
     "source_url": "https://www.bcci.tv/"},

    # ============ NEW SECTOR: Social Services ============
    {"slug": "ngo-staff", "name": "NGO & development sector staff",
     "sector": "Social Services & NGO", "value": 1700000, "pay": 320000, "edu": 4, "hire": 0,
     "source": "Bain India Philanthropy Report + Ministry of Home (FCRA)",
     "source_url": "https://fcraonline.nic.in/"},
    {"slug": "social-workers", "name": "Social workers (MSW / professional)",
     "sector": "Social Services & NGO", "value": 280000, "pay": 320000, "edu": 5, "hire": 1,
     "source": "NACSW + state social welfare depts",
     "source_url": "https://nacsw.org.in/"},
    {"slug": "child-welfare-workers", "name": "Child welfare & protection workers",
     "sector": "Social Services & NGO", "value": 95000, "pay": 280000, "edu": 4, "hire": 1,
     "source": "ICPS + Ministry of WCD",
     "source_url": "https://wcd.nic.in/"},
]
