"""
Score every Indian occupation on AI Exposure (0-10) via an LLM.

Reads:
  data/occupations.json   (master list of 90 occupations)
  pages/<slug>.md         (rich occupation descriptions, generated by process.py)

Writes:
  data/scores.json        ({slug: {score: int, rationale: str}})

Uses OpenRouter so any model is interchangeable. Default: google/gemini-2.5-flash
(same family Karpathy uses for the US version).

Usage:
  uv run python pipeline/score.py                      # score everything missing
  uv run python pipeline/score.py --force              # re-score all
  uv run python pipeline/score.py --only tcs-engineers # score one
  uv run python pipeline/score.py --model anthropic/claude-3.5-sonnet
"""

from __future__ import annotations
import argparse
import json
import os
import sys
import time
from pathlib import Path

import httpx
from dotenv import load_dotenv
from tqdm import tqdm

from make_prompt import (
    SYSTEM_PROMPT,
    make_user_prompt,
    EDU_LABELS,
    HIRE_LABELS,
)

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
PAGES_DIR = ROOT / "pages"
SCORES_PATH = DATA_DIR / "scores.json"

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
DEFAULT_MODEL = "google/gemini-2.5-flash"


def load_occupations() -> list[dict]:
    """Load the master occupation list and inflate human-readable labels."""
    with open(DATA_DIR / "occupations.json") as f:
        bundle = json.load(f)
    out = []
    for occ in bundle["occupations"]:
        occ = dict(occ)
        occ["edu_label"] = EDU_LABELS[occ["edu"]]
        occ["hire_label"] = HIRE_LABELS[occ["hire"]]
        out.append(occ)
    return out


def load_page_md(slug: str) -> str:
    """Load the rich markdown description for an occupation."""
    p = PAGES_DIR / f"{slug}.md"
    if not p.exists():
        # Fallback: minimal description from structured fields only.
        return "(No detailed description available — scoring from structured fields only.)"
    return p.read_text(encoding="utf-8")


def load_existing_scores() -> dict:
    if SCORES_PATH.exists():
        return json.loads(SCORES_PATH.read_text())
    return {}


def save_scores(scores: dict) -> None:
    SCORES_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCORES_PATH.write_text(json.dumps(scores, indent=2, ensure_ascii=False))


def score_one(client: httpx.Client, model: str, occupation: dict, page_md: str) -> dict:
    """Call the LLM and parse the JSON response."""
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENROUTER_API_KEY missing. Add it to .env or export it. "
            "Get one free at https://openrouter.ai/keys"
        )

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": make_user_prompt(occupation, page_md)},
        ],
        "response_format": {"type": "json_object"},
        "temperature": 0.2,
        "max_tokens": 400,
    }
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/Tonumoy/india-jobs",
        "X-Title": "India Jobs - AI Exposure Scoring",
    }

    for attempt in range(3):
        try:
            r = client.post(OPENROUTER_URL, json=payload, headers=headers, timeout=60.0)
            r.raise_for_status()
            content = r.json()["choices"][0]["message"]["content"]
            parsed = json.loads(content)
            # Defensive validation
            score = int(parsed.get("score"))
            if not (0 <= score <= 10):
                raise ValueError(f"score {score} out of range")
            rationale = str(parsed.get("rationale", "")).strip()
            return {"score": score, "rationale": rationale, "model": model}
        except (httpx.HTTPError, json.JSONDecodeError, ValueError, KeyError) as e:
            if attempt == 2:
                raise
            wait = 2 ** attempt
            print(f"  Retry {attempt+1}/3 after {wait}s for {occupation['slug']}: {e}", file=sys.stderr)
            time.sleep(wait)


def main():
    load_dotenv(ROOT / ".env")
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="Re-score even if cached")
    parser.add_argument("--only", help="Score only this slug (for testing)")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="OpenRouter model slug")
    parser.add_argument("--dry-run", action="store_true", help="Print plan, don't call API")
    args = parser.parse_args()

    occupations = load_occupations()
    scores = load_existing_scores()

    if args.only:
        occupations = [o for o in occupations if o["slug"] == args.only]
        if not occupations:
            print(f"No occupation with slug '{args.only}'.", file=sys.stderr)
            sys.exit(1)

    to_do = [o for o in occupations if args.force or o["slug"] not in scores]
    print(f"Plan: {len(to_do)}/{len(occupations)} to score with {args.model}.")
    if args.dry_run:
        for o in to_do:
            print(f"  - {o['slug']} ({o['name']})")
        return

    with httpx.Client() as client:
        for occ in tqdm(to_do, desc="Scoring"):
            page_md = load_page_md(occ["slug"])
            result = score_one(client, args.model, occ, page_md)
            scores[occ["slug"]] = result
            # Save incrementally so we never lose progress
            save_scores(scores)

    print(f"\nDone. {len(scores)} scores saved to {SCORES_PATH}")


if __name__ == "__main__":
    main()
