"""
Score every Indian occupation on AI Exposure (0-10) via an LLM.

Reads:
  data/occupations.json   (master list of 244 occupations)
  pages/<slug>.md         (rich occupation descriptions, generated by process.py)

Writes:
  data/scores.json        ({slug: {score, rationale, model}})

Uses OpenRouter so any model is interchangeable. Default model is a free-tier
OpenRouter offering so a vanilla run never costs money — pass --model to
override. On any single-model failure the FALLBACK_MODELS chain is tried in
order, so the run keeps going even when free providers rate-limit.

Usage:
  uv run python pipeline/score.py                      # score everything missing
  uv run python pipeline/score.py --force              # re-score all
  uv run python pipeline/score.py --only tcs-engineers # score one
  uv run python pipeline/score.py --model openai/gpt-oss-120b:free
  uv run python pipeline/score.py --model google/gemini-2.5-flash  # paid
"""

from __future__ import annotations
import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

import httpx
from dotenv import load_dotenv
from tqdm import tqdm

from make_prompt import (
    SYSTEM_PROMPT,
    make_user_prompt,
    EDU_LABELS,
    HIRE_LABELS,
)

ROOT = Path(__file__).parent.parent
DATA_DIR = ROOT / "data"
PAGES_DIR = ROOT / "pages"
SCORES_PATH = DATA_DIR / "scores.json"

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"
# Default to the strongest open-weight free model on OpenRouter as of
# 2026-05-29, per the Artificial Analysis Intelligence Index v4.0
# (Kimi K2.6: index 54, #1 open / #4 overall). Override with --model.
DEFAULT_MODEL = "moonshotai/kimi-k2.6:free"
# Fallback chain ordered by AA Intelligence Index (best → worst) so each
# occupation always gets the highest-quality model that's not currently
# rate-limited. Index scores annotated for next-time updates.
# Drop a model only if it returns 404; keep rate-limited (429) ones — the
# script retries with backoff before falling through.
FALLBACK_MODELS = [
    "deepseek/deepseek-v4-flash:free",          # 47
    "google/gemma-4-31b-it:free",               # 39
    "nvidia/nemotron-3-super-120b-a12b:free",   # 36
    "openai/gpt-oss-120b:free",                 # 33
    "google/gemma-4-26b-a4b-it:free",           # 31
    "nvidia/nemotron-3-nano-30b-a3b:free",      # 24
    "openai/gpt-oss-20b:free",                  # 24
    "z-ai/glm-4.5-air:free",                    # 23
    "qwen/qwen3-next-80b-a3b-instruct:free",    # 20
    "nousresearch/hermes-3-llama-3.1-405b:free",# ~17
    "nvidia/nemotron-nano-9b-v2:free",          # 15
    "meta-llama/llama-3.3-70b-instruct:free",   # 14
    "meta-llama/llama-3.2-3b-instruct:free",    # small / on-device tier
]


def load_occupations() -> list[dict]:
    """Load the master occupation list and inflate human-readable labels."""
    with open(DATA_DIR / "occupations.json") as f:
        bundle = json.load(f)
    out = []
    for occ in bundle["occupations"]:
        occ = dict(occ)
        occ["edu_label"] = EDU_LABELS[occ["edu"]]
        occ["hire_label"] = HIRE_LABELS[occ["hire"]]
        out.append(occ)
    return out


def load_page_md(slug: str) -> str:
    """Load the rich markdown description for an occupation."""
    p = PAGES_DIR / f"{slug}.md"
    if not p.exists():
        # Fallback: minimal description from structured fields only.
        return "(No detailed description available — scoring from structured fields only.)"
    return p.read_text(encoding="utf-8")


def load_existing_scores() -> dict:
    if SCORES_PATH.exists():
        return json.loads(SCORES_PATH.read_text(encoding="utf-8"))
    return {}


def save_scores(scores: dict) -> None:
    SCORES_PATH.parent.mkdir(parents=True, exist_ok=True)
    SCORES_PATH.write_text(json.dumps(scores, indent=2, ensure_ascii=False), encoding="utf-8")


def _strip_fences(s: str) -> str:
    """Strip ```json ... ``` (or plain ```) fences if the model wrapped them."""
    s = s.strip()
    if s.startswith("```"):
        s = s.split("\n", 1)[1] if "\n" in s else s[3:]
        if s.endswith("```"):
            s = s[:-3]
        s = s.strip()
        if s.startswith("json"):
            s = s[4:].strip()
    return s


def _repair_truncated_json(s: str) -> str:
    """Best-effort repair for JSON cut off mid-string by max_tokens.

    If the response ends inside an unterminated string, close the string and
    any unclosed object braces so json.loads can parse it.
    """
    # Walk to detect whether we ended inside a string
    in_str = False
    escape = False
    brace_depth = 0
    for ch in s:
        if escape:
            escape = False
            continue
        if ch == "\\":
            escape = True
            continue
        if ch == '"':
            in_str = not in_str
            continue
        if in_str:
            continue
        if ch == "{":
            brace_depth += 1
        elif ch == "}":
            brace_depth -= 1
    repaired = s
    if in_str:
        repaired += '"'
    repaired += "}" * max(brace_depth, 0)
    return repaired


def _regex_extract(s: str) -> dict | None:
    """Last-resort: pull score + rationale from raw text with regex."""
    m = re.search(r'"score"\s*:\s*(\d+)', s)
    if not m:
        return None
    score = int(m.group(1))
    if not (0 <= score <= 10):
        return None
    r = re.search(r'"rationale"\s*:\s*"((?:[^"\\]|\\.)*)', s)
    rationale = r.group(1).encode().decode("unicode_escape", errors="ignore") if r else ""
    return {"score": score, "rationale": rationale.strip()}


def _parse_response(content: str) -> dict:
    """Parse the model's content into {score, rationale}. Raises ValueError on failure."""
    content = _strip_fences(content)
    # Try direct, then repaired, then regex
    for candidate in (content, _repair_truncated_json(content)):
        try:
            parsed = json.loads(candidate)
            raw = parsed.get("score")
            if raw is None:
                continue
            score = int(raw)
            if not (0 <= score <= 10):
                continue
            return {"score": score, "rationale": str(parsed.get("rationale", "")).strip()}
        except (json.JSONDecodeError, TypeError, ValueError):
            continue
    extracted = _regex_extract(content)
    if extracted is not None:
        return extracted
    raise ValueError(f"could not extract score from response: {content[:200]!r}")


def score_one(client: httpx.Client, model: str, occupation: dict, page_md: str,
              max_attempts: int = 5, rate_limit_attempts: int = 2) -> dict:
    """Call the LLM and parse the JSON response.

    Two retry budgets:
      * `max_attempts` (5): for parse / timeout / transient HTTP errors — these
        we want to retry because the model is responsive but the response was
        malformed, so a fresh attempt might land cleanly.
      * `rate_limit_attempts` (2): for 429s — a 429 means *this provider* is
        busy; spending 75 seconds backing off here is worse than letting the
        outer fallback chain hand the job to a non-busy provider after just
        one short retry. The chain IS the rate-limit recovery mechanism.
    """
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENROUTER_API_KEY missing. Add it to .env or export it. "
            "Get one free at https://openrouter.ai/keys"
        )

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://github.com/Tonumoy/India-Jobs",
        "X-Title": "India Jobs - AI Exposure Scoring",
    }

    last_err: Exception | None = None
    rate_limit_seen = 0
    for attempt in range(max_attempts):
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": make_user_prompt(occupation, page_md)},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.2 if attempt == 0 else 0.4,
            # Generous budget so the rationale never truncates. Rubric caps it
            # at 75 words but free models often overshoot.
            "max_tokens": 1200,
        }
        try:
            r = client.post(OPENROUTER_URL, json=payload, headers=headers, timeout=90.0)
            if r.status_code == 429:
                # Rate-limited — back off briefly, then fall through to the
                # next model in the chain. Don't burn the full retry budget
                # waiting for one busy provider.
                rate_limit_seen += 1
                if rate_limit_seen >= rate_limit_attempts:
                    last_err = RuntimeError("rate limited")
                    print(f"  [429 x{rate_limit_seen}] {occupation['slug']} on {model.split('/')[-1]}, falling through",
                          file=sys.stderr)
                    break  # Exit attempts loop, raise to outer fallback chain
                wait = 5 * rate_limit_seen
                print(f"  [429] {occupation['slug']} on {model.split('/')[-1]} attempt {rate_limit_seen}/{rate_limit_attempts}, sleeping {wait}s",
                      file=sys.stderr)
                time.sleep(wait)
                last_err = RuntimeError("rate limited")
                continue
            r.raise_for_status()
            body = r.json()
            try:
                content = body["choices"][0]["message"]["content"]
            except (KeyError, IndexError, TypeError):
                content = None
            if content is None or not str(content).strip():
                # Some providers return null content on safety filter / empty completion.
                raise ValueError(f"empty response from {model}")
            parsed = _parse_response(content)
            return {"score": parsed["score"], "rationale": parsed["rationale"], "model": model}
        except (httpx.HTTPError, ValueError, KeyError, TypeError) as e:
            last_err = e
            wait = min(2 ** attempt, 8)
            print(f"  Retry {attempt+1}/{max_attempts} after {wait}s for {occupation['slug']}: {e}",
                  file=sys.stderr)
            time.sleep(wait)
    assert last_err is not None
    raise last_err


def main():
    load_dotenv(ROOT / ".env")
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="Re-score even if cached")
    parser.add_argument("--only", help="Score only this slug (for testing)")
    parser.add_argument("--model", default=DEFAULT_MODEL, help="OpenRouter model slug")
    parser.add_argument("--dry-run", action="store_true", help="Print plan, don't call API")
    args = parser.parse_args()

    occupations = load_occupations()
    scores = load_existing_scores()

    if args.only:
        occupations = [o for o in occupations if o["slug"] == args.only]
        if not occupations:
            print(f"No occupation with slug '{args.only}'.", file=sys.stderr)
            sys.exit(1)

    to_do = [o for o in occupations if args.force or o["slug"] not in scores]
    print(f"Plan: {len(to_do)}/{len(occupations)} to score with {args.model}.")
    if args.dry_run:
        for o in to_do:
            print(f"  - {o['slug']} ({o['name']})")
        return

    failures = []
    fallbacks_used = []
    # Try the user-chosen model first, then walk the fallback chain. Drop any
    # fallback that duplicates the primary so we don't waste a retry on the same model.
    model_chain = [args.model] + [m for m in FALLBACK_MODELS if m != args.model]

    with httpx.Client() as client:
        for occ in tqdm(to_do, desc="Scoring"):
            page_md = load_page_md(occ["slug"])
            result = None
            last_err: Exception | None = None
            for idx, model in enumerate(model_chain):
                try:
                    result = score_one(client, model, occ, page_md)
                    if idx > 0:
                        fallbacks_used.append((occ["slug"], model))
                        print(f"  [fallback] {occ['slug']} scored via {model}", file=sys.stderr)
                    break
                except Exception as e:
                    last_err = e
                    print(f"  [model {model} failed for {occ['slug']}] {e}", file=sys.stderr)
            if result is None:
                print(f"  [SKIP — all models failed] {occ['slug']}: {last_err}", file=sys.stderr)
                failures.append(occ["slug"])
                continue
            scores[occ["slug"]] = result
            # Save incrementally so we never lose progress
            save_scores(scores)

    print(f"\nDone. {len(scores)} scores saved to {SCORES_PATH}")
    if fallbacks_used:
        print(f"  {len(fallbacks_used)} occupation(s) scored via fallback model.")
    if failures:
        print(f"  {len(failures)} occupation(s) kept their previous score: {', '.join(failures)}")


if __name__ == "__main__":
    main()
